name: Build and Notify Frontend to Run E2E

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Frontend Repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/josbell/todo/dispatches \
          -d '{"event_type": "backend-deployed"}'