name: Build and Notify Frontend to Run E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: write 

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Frontend Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/josbell/todo/dispatches \
          -d '{"event_type": "backend-deployed"}'